### ISSUE TITLE
Food items idea.

### ISSUE THREAD

**Issue by alex256z** [TheRanker/Outlandish-Revelations#4]
There is lots of food items in this great modpack, but most of it gets useless when player found a way to constantly craft one meal with lots of saturation restore points. Suggestion is to add "Spice of Life: Apple Pie Edition" (or "Spice of Life: Valheim Edition") to create needs for player to eat all food items in the game to get some extra health points.

**Comment by TheRanker** [comment]
We've had a system ... We also removed the Hungary bar .. then we removed both them and used another mod for some food issues.  But we also removed that due to other things in the mod not being "up to par" with what I want it to do.  

So your totally right! 
We have nothing but a vestige for eating food. And no way to officially generate/create more hearts.  

Though I don't want to break eating food or the modpack by adding some mods. . the ones your recommended are very interesting. 

I'm aware of spice of life of course,  but I have never used. 

So I'm reviewing your two suggestions and looking for best route to go.  

If you have personal ideas or experience with both of these, I'll gladly take your opinion.  

I understand valheim one.  3 food slots (hard to keep inventory slots free , and 3 for food will be very very hard.  As a lot of drops in this modpack.  Hence danknull , backpacks, etc. 

Carrot one seems like realistic without breaking or ruining gameplay and progression flow.

**Comment by alex256z** [comment]
> Carrot one seems like realistic without breaking or ruining gameplay and progression flow.

I'm was played with Carrot in other modpack with lots of food, and it need some tweaking in config, because progression in adding hearts is non-linear - at start you gets half-heart after eating, say, 4 different food, then 6, then 10, then 16 etc., so at earlygame you can get almost 2/3 of all avialable hearts. So i tweaked my config for Carrot Edition to have linear progression - it adds half-heart every 15 never before eaten foods. In modpack that i played was around 750 different food items, so if taste it all you have +50 half-hearts = +25 hearts. Now i found "Apple Pie Edition", which boosts large meal foods and nerfs food with small saturation, so you have to craft meals.

> I understand valheim one. 3 food slots (hard to keep inventory slots free , and 3 for food will be very very hard. As a lot of drops in this modpack. Hence danknull , backpacks, etc.

About "Spice of Life: Valheim Edition" i was wrong. I think it is not good idea to have 3 food types in inventory.

 So i think best way is Apple Pie or Carrot, tweaked to add not too much hearts (or in the endgame player will be like undestructible monter 😈).

Also Carrot and Apple Pie can set starting health to less than 10 hearts, and earlygame will be a bit harder.

**Comment by KazKazath** [comment]
Ah yes, the tendrils of GTNH will forever sink it's claws into us

**Comment by TheRanker** [comment]
I'm gonna toss in another suggestion
https://www.curseforge.com/minecraft/mc-mods/spice-of-life-onion

SOL Onion.
 @alex256z any opinion of this one? I'd rather this. It's potato 1.16 version updated for 1.20. 

Adds variation to keep your heart's up.  If no variation you lose hearts. And need to try others to keep it up. 

I also have a mod that includes an OP item if all food in modpack is consumed. The mod is vestiges of present.  Adds other items too.  But would help work towards that goal.   

So we have 

Carrot
Apple Pie
Onion 

To decode /choose from. Or combine. 

Any thoughts?

**Comment by alex256z** [comment]
Yeah, GTNH rulez! 😈! ..but not for 1.20.1 😢.

> I also have a mod that includes an OP item if all food in modpack is consumed. The mod is vestiges of present.
Thats nice!
.......
Sooo.. after abit of testing:
1) Onion and Apple Pie is almost the same things, Onion is easier to configure, so Apple Pie is out. This variant is for some food management in inventory (at some level it adds positive permanent potion effects, but it is too OP and can be deleted in config).
2) Carrot is the easy one - "CollectEmAll" and get some hearts in progress.

Thoughts: modpack is Greg-oriented, so many work(i mean fun) in the factory expected, that mean food management will be annoing, but a bit more health will be a small bonus for collecting food, and Carrot is good for that. Lets say, +10 hearts after eating most food in modpack (1593 OMG!!). Linear progression will be ok (+1 heart per 150 different food items).

**Comment by TheRanker** [comment]
Yeah it's a lot of foods. Hahahaha 

What about using them both (🥕 and 🧅) ?  I don't mind the work to configure them. 

They are compatible with eachother. But may be to much as well cause there's a lot of focus in the tech side of things and having them focus on finding different food to get hearts back can be a bit annoying or a bit much. 

 I don't want any ... "Tough as nails" vibe at all. I don't like that kind of strict gameplay.

**Comment by alex256z** [comment]
> What about using them both (🥕 and 🧅) ? I don't mind the work to configure them.
> 
> They are compatible with eachother. But may be to much as well cause there's a lot of focus in the tech side of things and having them focus on finding different food to get hearts back can be a bit annoying or a bit much.

I was wrong about Carrot changing starting health to lower values(tested it), it only permanently adds additional hearts.

So we can use Carrot to add +10 hearts as small bonus, and we can configure Onion to add +2..+3 hearts for eating only good food. And if someone don't want to collect food - he still will have default 10 hearts without any food management. I do not insist on anything, just a suggest.

"Tough as nails" mod will be hell for everyone😨, especially season changing(makes a big mess with snow in warm biomes).

**Comment by TheRanker** [comment]
> "Tough as nails" mod will be hell for everyone😨, especially season changing(makes a big mess with snow in warm biomes).

well that was indicated to reference its hunger and thirst, energy and all that modifications to the player system , not to mention the enviroment effects it has lol

> So we can use Carrot to add +10 hearts as small bonus, and we can configure Onion to add +2..+3 hearts for eating only good food. And if someone don't want to collect food - he still will have default 10 hearts without any food management. I do not insist on anything, just a suggest.

ill come up with something. running some tests and checking what i can do with them as we speak :)

**Comment by TheRanker** [comment]
so im not gonna use onion ... and just use carrot. 

and this is my; first draft of the setup 
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 5
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 2
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [15, 50, 100, 200, 450, 750, 1000, 1250, 1500, 1593]
	@alex256z

**Comment by alex256z** [comment]
Only Carrot is good👍.
Base 5 hearts is perfect.
So with your setup we get 25 hearts in the end.
What about progression by 1 heart with fast progress from 5 to 10 hearts and then te the end?

heartsPerMilestone = 1
milestones = [10, 25, 40, 55, 80, 150, 250, 350, 450, 550, 650, 750, 850, 950, 1050, 1150, 1250, 1350, 1450, 1550]

*1550(not 1593) to prevent some "I cant find these goddam two foods!!!" to get last heart.

**Comment by TheRanker** [comment]
> Only Carrot is good👍. Base 5 hearts is perfect. So with your setup we get 25 hearts in the end. What about progression by 1 heart with fast progress from 5 to 10 hearts and then to the end?
> 
> heartsPerMilestone = 1 milestones = [10, 25, 40, 55, 80, 150, 250, 350, 450, 550, 650, 750, 850, 950, 1050, 1150, 1250, 1350, 1450, 1550]
> 

agreed

> *1550(not 1593) to prevent some "I cant find these goddam two foods!!!" to get last heart.

very good point. never thought about that lol

done and implemented for next update :)

**Comment by alex256z** [comment]
Thanks!😻
