### ISSUE TITLE
Enchanting table

### ISSUE THREAD

**Issue by alex256z** [TheRanker/Outlandish-Revelations#9]
Is Enchanting table disabled for items? Because it only work on books. Is it bugged or it configured like so? If it configured - it is OK.

**Comment by TheRanker** [comment]
Haha gotta use a book , then book+item in a anvil. ;)

To be 100% honest, it's a bug. 

And been many updates and versions in , and I still can't find the cause.

**Comment by alex256z** [comment]
> Haha gotta use a book , then book+item in a anvil. ;)
> 
> To be 100% honest, it's a bug.
> 
> And been many updates and versions in , and I still can't find the cause.

It is not a problem, i think)). It is some kind of balance, because when you die, you not losing XP(and items), and this bug let's you spend more XP to get needed enchantement. 😎
